### ISSUE TITLE
[Feature Request] Add default theme

### ISSUE THREAD

**Issue by proudmuslim-dev** [onagre-launcher/onagre#32]
Running Onagre without having a theme in the config directory currently results in this error:
```rust
Unable to load user theme: Unable to find theme settings file /home/twilight/.config/onagre/theme.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/subscriptions/pop_launcher.rs:87:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It would be preferable for it to just put a default theme there and notify the user

**Comment by oknozor** [comment]
This is strange, currently your are supposed to get only the following message : 
```
Unable to load user theme: Unable to find theme settings file /home/okno/.config/onagre/theme.toml
```
While the message needs to be more explicit, onagre should start with a default theme : 
![image](https://user-images.githubusercontent.com/24563836/137805618-a6c39398-cf60-42ff-ab0f-a895d11b2321.png)

Can you upgrade and try again ?

**Comment by proudmuslim-dev** [comment]
Ah I see, giving it a shot now
