### ISSUE TITLE
Add a some error context to indicate when pop-launcher is missing

### ISSUE THREAD

**Issue by markstos** [onagre-launcher/onagre#37]
**Is your feature request related to a problem? Please describe.**

Today I installed `onagre` for the first time and tried to start it but it immediately crashed:

```
onagre
Unable to load user theme: Unable to find theme settings file /home/mark/.config/onagre/theme.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/subscriptions/pop_launcher.rs:87:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Describe the solution you'd like**

I expected the tool to work with a no configuration file. Either some defaults should be used, or it should see that my config file is missing and copy a default config file into place and then start.

**Comment by oknozor** [comment]
Hello @markstos onagre does launch without a config file. 
The thread panic occurs because you don't have [pop-launcher](https://github.com/pop-os/launcher) installed on your system I think.

**Comment by markstos** [comment]
Thanks. Perhaps it could fail more gracefully if pop launcher does not exist.
