### ISSUE TITLE
icons don't render after I install Nautilus

### ISSUE THREAD

**Issue by VarLad** [onagre-launcher/onagre#53]
**Describe the bug**
It works fine but as soon as I install Nautilus, I get black squares for icons. This is on Fedora 36

**Config** 
`theme.scss`
```
.onagre {
  --exit-unfocused: false;
  height: 250px;
  width: 400px;
  --icon-theme: "Adwaita";
  --icon-size: 22px;
  font-size: 12px;
  background: #2E3440;
  color: #81a1c1;
  border-color: #2E3440;
  border-radius: 25%;
  border-width: 4px;
  padding: 10px;

  .container {
    .search {
      --spacing: 1;
      background: #3b4252;
      color: #d8dee9;
      padding: 4px;
      --height: fill-portion 1;
      .plugin-hint {
        font-size: 9px;
        color: #bf616a;
        padding: 4px;
        border-width: 2px;
        border-color: #bf616a;
        border-radius: 5%;
        background: #4c566a;
        --align-x: center;
        --align-y: center;
        --width: fill-portion 2;
        --height: fill;
      }

      .input {
        --width: fill-portion 11;
      }

    }

    .rows {
      --height: fill-portion 5;
      .row-selected {
        background: #2E3440;
        color: #ebcb8b;
        --spacing: 3px;
        --align-y: center;
      }
    }

    .scrollable {
      .scroller {
        color: #4c566a;
      }
    }
  }
}
```

**To Reproduce**
Install Nautilus, open Onagre

**Expected behavior**
Icons render

**Screenshots**
![image](https://user-images.githubusercontent.com/51269425/196232349-44023047-551b-4437-8556-7370aff7dd2d.png)

**Window manager (please complete the following information):**
 - Window manager: GNOME 42

**Comment by DanielVoogsgerd** [comment]
I'm also running into this issue. However, I don't have nautilus installed. I can imagine that it would be an icon-related dependency of nautilus.

**Comment by DanielVoogsgerd** [comment]
Related wiki page that solved my issue: https://github.com/oknozor/onagre/wiki/Troubleshooting#icon-are-not-rendered
