### ISSUE TITLE
Option to include binaries from `$PATH` in same search as desktop entries

### ISSUE THREAD

**Issue by simvux** [onagre-launcher/onagre#56]
**Is your feature request related to a problem? Please describe.**
I mainly use binaries in `$PATH` to run my programs, but I'd like to start using desktop entries as well due to the inclusion of pretty icons. However; switching to a launcher that uses desktop entries causes all of my custom scripts and wrappers to no longer appear in search. 

**Describe the solution you'd like**
I would like to be able to have both desktop entries and binaries in `$PATH` to show up by default in the same search.
The ideal would be to also filter out those binaries that *also* have a desktop entry, so that there won't be any duplicates. 

**Describe alternatives you've considered**
Alternatively; the `run` prefix could be set up to provide search results from `$PATH`. 
This might already be a feature but the `run` prefix doesn't work for me for some reason so I wouldn't know...

**Comment by jokeyrhyme** [comment]
I think the idea here would be to add a pop-launcher plugin that looks up PATH executables for you

Interesting that there isn't already something to do this: https://github.com/lucas-dclrcq/awesome-pop-launcher

The included/official `run` plugin doesn't seem to do any searching or completion, it just takes anything after the keyword and executes: https://github.com/pop-os/launcher/blob/master/plugins/src/terminal/mod.rs

**Comment by oknozor** [comment]
Closing this since I could be implemented in a plugin.
