### ISSUE TITLE
Ability to pass plugin string as parameter so as to launch gui in specific mode

### ISSUE THREAD

**Issue by MostHated** [onagre-launcher/onagre#58]
**Is your feature request related to a problem? Please describe.**
What would really make this much more usable in my opinion (as opposed to just using the normal launcher, or app window, etc) would be to be able to launch it in a specific plugin mode from the get-go. Similar to launching Rofi with run, drun, etc.

Example:

```sh 
onagre run    # Launch window ready to accept a terminal command  
```

**Comment by juanolon** [comment]
i have made a pull request adding this feature #68 ;)

**Comment by oknozor** [comment]
This is now implemented.
Closing for now, Thanks a lot @juanolon :)
