### ISSUE TITLE
NOT WORKING !!

### ISSUE THREAD

**Issue by mohammed-saleh2007** [onagre-launcher/onagre#74]
**Describe the bug**
not working

**To Reproduce**
just typed in terminal onagre

**Expected behavior**
[mohamed@archlinux ~/src/onagre]$ RUST_BACKTRACE=full onagre
2024-02-10T21:27:48.728645Z  INFO onagre: Starting onagre
thread 'main' panicked at src/app/subscriptions/pop_launcher.rs:77:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x55a89d83d98a - std::backtrace_rs::backtrace::libunwind::trace::hdc4233b41dc1b9cd
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55a89d83d98a - std::backtrace_rs::backtrace::trace_unsynchronized::h120e68387b28a22e
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a89d83d98a - std::sys_common::backtrace::_print_fmt::ha2c8f57bdb4df8b5
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55a89d83d98a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h29fd9f59e5b156f6
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55a89d32a750 - core::fmt::rt::Argument::fmt::he2faf549fd7f6050
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/rt.rs:142:9
   5:     0x55a89d32a750 - core::fmt::write::hb003a2722f32aba9
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/mod.rs:1120:17
   6:     0x55a89d803d2c - std::io::Write::write_fmt::h5f2291dd5789d9ad
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/io/mod.rs:1810:15
   7:     0x55a89d83f54f - std::sys_common::backtrace::_print::hc72c414d550b4638
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55a89d83f54f - std::sys_common::backtrace::print::h7bda25037860cb99
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55a89d83edc3 - std::panicking::default_hook::{{closure}}::hae510b2efd1217a7
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:272:22
  10:     0x55a89d83fd79 - std::panicking::default_hook::h67e28ed4cf565cf3
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:292:9
  11:     0x55a89d83fd79 - std::panicking::rust_panic_with_hook::h340d3254c4a80530
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:779:13
  12:     0x55a89d83f8a0 - std::panicking::begin_panic_handler::{{closure}}::h20aebccdeba64ffc
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:657:13
  13:     0x55a89d83f7f6 - std::sys_common::backtrace::__rust_end_short_backtrace::hfacd59953039e580
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55a89d83f7ef - rust_begin_unwind
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:645:5
  15:     0x55a89d103664 - core::panicking::panic_fmt::h3b0fc9e47c437efe
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/panicking.rs:72:14
  16:     0x55a89d103bd2 - core::result::unwrap_failed::h36d2e720ec9c5dcb
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/result.rs:1649:5
  17:     0x55a89d26d0d0 - <onagre::app::subscriptions::pop_launcher::PopLauncherSubscription as iced_futures::subscription::Recipe>::stream::heea728c4e8c0153c
  18:     0x55a89d251c78 - <iced_futures::subscription::Map<A,B> as iced_futures::subscription::Recipe>::stream::h13748551ac61061c
  19:     0x55a89d194586 - iced_futures::runtime::Runtime<Executor,Sender,Message>::track::h590cc7dcc7c166a2
  20:     0x55a89d1648f3 - iced_winit::application::run_instance::{{closure}}::h013cd173506d4f5c
  21:     0x55a89d17ad57 - iced_winit::application::run::{{closure}}::h95f640158db6b5ac
  22:     0x55a89d175c3a - iced_winit::application::run::hea902e948fd02128
  23:     0x55a89d270ebf - onagre::app::run::hf621256a86d91f1e
  24:     0x55a89d296d2d - onagre::main::h163d445ef536ae5a
  25:     0x55a89d1c2723 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc54856df397d9ed
  26:     0x55a89d29d1a6 - main
  27:     0x7a74acab6cd0 - <unknown>
  28:     0x7a74acab6d8a - __libc_start_main
  29:     0x55a89d157905 - _start
  30:                0x0 - <unknown>
warning: queue 0x55a89ff17ae0 destroyed while proxies still attached:
  xdg_wm_base@20 still attached
  wl_output@14 still attached
  wl_seat@13 still attached
  xdg_activation_v1@12 still attached
  wp_viewporter@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zwp_relative_pointer_manager_v1@8 still attached
  zxdg_decoration_manager_v1@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Window manager (please complete the following information):**
 - Window manager: sway on Archlinux, btw

**Additional context**
that is the full debugging log:
[mohamed@archlinux ~]$ RUST_BACKTRACE=full onagre
2024-02-10T21:28:26.832862Z  INFO onagre: Starting onagre
thread 'main' panicked at src/app/subscriptions/pop_launcher.rs:77:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x5cca1647498a - std::backtrace_rs::backtrace::libunwind::trace::hdc4233b41dc1b9cd
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5cca1647498a - std::backtrace_rs::backtrace::trace_unsynchronized::h120e68387b28a22e
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5cca1647498a - std::sys_common::backtrace::_print_fmt::ha2c8f57bdb4df8b5
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5cca1647498a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h29fd9f59e5b156f6
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5cca15f61750 - core::fmt::rt::Argument::fmt::he2faf549fd7f6050
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/rt.rs:142:9
   5:     0x5cca15f61750 - core::fmt::write::hb003a2722f32aba9
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/mod.rs:1120:17
   6:     0x5cca1643ad2c - std::io::Write::write_fmt::h5f2291dd5789d9ad
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/io/mod.rs:1810:15
   7:     0x5cca1647654f - std::sys_common::backtrace::_print::hc72c414d550b4638
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5cca1647654f - std::sys_common::backtrace::print::h7bda25037860cb99
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5cca16475dc3 - std::panicking::default_hook::{{closure}}::hae510b2efd1217a7
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:272:22
  10:     0x5cca16476d79 - std::panicking::default_hook::h67e28ed4cf565cf3
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:292:9
  11:     0x5cca16476d79 - std::panicking::rust_panic_with_hook::h340d3254c4a80530
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:779:13
  12:     0x5cca164768a0 - std::panicking::begin_panic_handler::{{closure}}::h20aebccdeba64ffc
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:657:13
  13:     0x5cca164767f6 - std::sys_common::backtrace::__rust_end_short_backtrace::hfacd59953039e580
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5cca164767ef - rust_begin_unwind
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:645:5
  15:     0x5cca15d3a664 - core::panicking::panic_fmt::h3b0fc9e47c437efe
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/panicking.rs:72:14
  16:     0x5cca15d3abd2 - core::result::unwrap_failed::h36d2e720ec9c5dcb
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/result.rs:1649:5
  17:     0x5cca15ea40d0 - <onagre::app::subscriptions::pop_launcher::PopLauncherSubscription as iced_futures::subscription::Recipe>::stream::heea728c4e8c0153c
  18:     0x5cca15e88c78 - <iced_futures::subscription::Map<A,B> as iced_futures::subscription::Recipe>::stream::h13748551ac61061c
  19:     0x5cca15dcb586 - iced_futures::runtime::Runtime<Executor,Sender,Message>::track::h590cc7dcc7c166a2
  20:     0x5cca15d9b8f3 - iced_winit::application::run_instance::{{closure}}::h013cd173506d4f5c
  21:     0x5cca15db1d57 - iced_winit::application::run::{{closure}}::h95f640158db6b5ac
  22:     0x5cca15dacc3a - iced_winit::application::run::hea902e948fd02128
  23:     0x5cca15ea7ebf - onagre::app::run::hf621256a86d91f1e
  24:     0x5cca15ecdd2d - onagre::main::h163d445ef536ae5a
  25:     0x5cca15df9723 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc54856df397d9ed
  26:     0x5cca15ed41a6 - main
  27:     0x7a3c0527ccd0 - <unknown>
  28:     0x7a3c0527cd8a - __libc_start_main
  29:     0x5cca15d8e905 - _start
  30:                0x0 - <unknown>
warning: queue 0x5cca16c6bae0 destroyed while proxies still attached:
  xdg_wm_base@20 still attached
  wl_output@14 still attached
  wl_seat@13 still attached
  xdg_activation_v1@12 still attached
  wp_viewporter@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zwp_relative_pointer_manager_v1@8 still attached
  zxdg_decoration_manager_v1@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by oknozor** [comment]
YOU NEED TO INSTALL [pop-launcher](https://github.com/pop-os/launcher) AS STATED IN THE README.
