### ISSUE TITLE
onagre 1.1.0: crashes on start with "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by eljamm** [onagre-launcher/onagre#83]
**Describe the bug**
Running onagre 1.1.0 crashes on start with the following output:

```console
2024-04-19T17:09:50.193906Z  INFO onagre: Starting onagre
2024-04-19T17:09:50.193990Z ERROR onagre::app::style: Failed to parse theme "/home/user/.config/onagre/theme.scss":
 Failed to open config file
2024-04-19T17:09:50.194000Z  WARN onagre::app::style: Failing back to default theme
thread 'main' panicked at /home/kuroko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.3/src/inst
ance.rs:521:39:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is the full log:
`RUST_BACKTRACE=full ./target/debug/onagre &> onagre.log` -> [onagre.log](https://github.com/onagre-launcher/onagre/files/15043535/onagre.log)

**Config** 
No config/theme. Putting a theme removes the `Failed to parse theme` error, but the program still crashes.

**To Reproduce**
1. cargo build --release --locked
2. ./target/release/onagre

**Expected behavior**
The program opens.

**System Information**
 - Window manager: Gnome (Wayland)
 - Distro: NixOS, 24.05 (Uakari)

**Additional context**
Tried running 1.0.0 and that version opens normally.

**Comment by Rairosu** [comment]
`wgpu` requires you to put `vulkan-loader` from nixpkgs in your `LD_LIBRARY_PATH`
