### ISSUE TITLE
Spliting the configuration to multiple files

### ISSUE THREAD

**Issue by salahoued** [onagre-launcher/onagre#88]
**Is your feature request related to a problem? Please describe.**
Not related to a problem,

**Describe the solution you'd like**
Is there a way to split the configuration into multiple files and then use `import`, `include` or `use` to import the other files into
`theme.scss`.
Like having a `colors.scss` and `theme.scss`, then import colors in `theme.scss`

**Describe alternatives you've considered**
No alternatives

**Additional context**
I'm using `tinty` a `base16` color scheme generator, and I'd like a use the generated colors automatically for `onagre`

**Comment by oknozor** [comment]
It is not possible right now. Onagre uses its own parser for the theme file. We uses the scss extension to have free syntax higliting but it is not really scss. 

To get imports and includes you'd have to implement this from scratch in the theme parse.

A PR would be welcome, but lately I don't have time to tackle such a feature.

**Comment by salahoued** [comment]
OK, Thanks
